require("plugins")
require("options")
require("autocmds")
require("mappings")

require("config/cmp").setup()
require("config/lsp").setup()
require("config/treesitter")
require("config/telescope")
require("config/lualine")
